### ISSUE TITLE
Doesn't report missing audio codecs, hangs indefinitely.

### ISSUE THREAD

**Issue by kkartaltepe** [SirCmpwn/osuweb#1]
Calls to ```OsuAudio.decode``` on a browser that doesn't support mp3/aac results in the program hanging and endlessly spitting errors. You should report to the user that their browser doesn't support the codec they are trying to use. Happens for me on firefox and chromium both without mp3 support. Attempting on Google Chrome with mp3 support gets through that issue.

**Comment by SirCmpwn** [comment]
The latest versions of Firefox and Chrome both support mp3 decoding, so I didn't bother. Feel free to send a pull request fixing this but I don't really care otherwise.
