### ISSUE TITLE
Uh you just leaked your MD5 password hash.

### ISSUE THREAD

**Issue by Pepperrika** [SirCmpwn/osuweb#10]
in notes.txt:
ha is your password hash not the beatmap md5
c is the beatmap md5 not the password hash
and...
h is your password hash
and c is the beatmap hash.
i would recommend you change your password now or your gonna prob get hacked by someone.

**Comment by SirCmpwn** [comment]
I've long since changed my password.

**Comment by Pepperrika** [comment]
Welp i just wanted to warn you about that.

**Comment by HazeDevelopment** [comment]
That still doesn't take away that it's dumb

**Comment by SirCmpwn** [comment]
Yeah, it is dumb that osu sends your password hash in the query strings of HTTP requests.
