### ISSUE TITLE
Stuck on "Loading map..."

### ISSUE THREAD

**Issue by fb39ca4** [SirCmpwn/osuweb#3]
Dropped a beatmap into the window, and it never finishes loading. Tried with the same results on Firefox 39, Chrome 44, and IE 11.

**Comment by SirCmpwn** [comment]
Which beatmap?

**Comment by fb39ca4** [comment]
I was trying https://osu.ppy.sh/s/258193. Oddly enough, today it is working - I just tried it in Firefox and Chrome.

**Comment by nyanpasu** [comment]
Are you zipping the contents or the directory?

**Comment by nyanpasu** [comment]
Eh, I guess a file check can avoid this.
